name: Artifact Workflow

on: push

jobs:
  artifact-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
        env:
          ARTIFACT_NAME: artifact
